### ISSUE TITLE
Click to close. 

### ISSUE THREAD

**Issue by rgfx** [octopuscreative/FancySelect#18]
When you click the arrow again, it should close like a default selectbox. I am not much of a programmer, prop can be done with a toggleclass. 

Thanks

**Comment by thegregthomp** [comment]
This issue seems to come from: `trigger.on('close.fs'` firing before `trigger.on('click.fs`. What's happening is, if you hold down your mouse on close, it fires close then refires click, essentially closing then re-opening it.

**Comment by thegregthomp** [comment]
haven't done too much testing but...

changing line 71 `trigger.on('click.fs'), function()` to `trigger.on('mousedown.fs', function(e) {
        event.preventDefault();' Should do the trick
