### ISSUE TITLE
What is the best way to have 2 different select styles?

### ISSUE THREAD

**Issue by nachores** [octopuscreative/FancySelect#72]
Hi!

The plugin is awesome.

I was wondering if I could have 2 different fancy selects within a page. I mean, different css properties.

Of course I know I could, but I don't know if there is a quick and easy way to do it.

Could you help me?

Thanks a lot!

**Comment by paulstraw** [comment]
Probably the quickest way to do that right now is have a wrapper div around your select, and style based on a class of that div. Something like this:

```
<div class="fs-style1">
    <select>…</select>
</div>

<div class="fs-style2">
    <select>…</select>
</div>
```

**Comment by nachores** [comment]
Yes, I'll do that. Thanks a lot!
